/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author paulp
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ActVentana v1;
    private PerVentana v2;
    private PeliVentana v3;
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        v1 = new ActVentana();
        v2 = new PerVentana();
        v3 = new PeliVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCrearActor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCrearPelicula = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCrearPersonaje = new javax.swing.JMenuItem();
        menuModificarPersonaje = new javax.swing.JMenuItem();
        menuEliminarPersonaje = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jMenu1.setText("Actor");

        menuCrearActor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuCrearActor.setText("Crear Actor");
        menuCrearActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearActorActionPerformed(evt);
            }
        });
        jMenu1.add(menuCrearActor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pelicula");

        menuCrearPelicula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuCrearPelicula.setText("Crear Pelicula");
        menuCrearPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearPeliculaActionPerformed(evt);
            }
        });
        jMenu2.add(menuCrearPelicula);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Personaje");

        menuCrearPersonaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuCrearPersonaje.setText("Crear Personaje");
        menuCrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearPersonajeActionPerformed(evt);
            }
        });
        jMenu3.add(menuCrearPersonaje);

        menuModificarPersonaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuModificarPersonaje.setText("Modificar Personaje");
        menuModificarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarPersonajeActionPerformed(evt);
            }
        });
        jMenu3.add(menuModificarPersonaje);

        menuEliminarPersonaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuEliminarPersonaje.setText("Eliminar Personaje");
        menuEliminarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarPersonajeActionPerformed(evt);
            }
        });
        jMenu3.add(menuEliminarPersonaje);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCrearPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearPeliculaActionPerformed
        escritorio.add(v3);
        v3.setVisible(true);
    }//GEN-LAST:event_menuCrearPeliculaActionPerformed

    private void menuCrearActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearActorActionPerformed
        escritorio.add(v1);
        v1.setVisible(true);
    }//GEN-LAST:event_menuCrearActorActionPerformed

    private void menuCrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearPersonajeActionPerformed
        escritorio.add(v2);
        v2.setVisible(true);
        v2.getBtnCrear().setEnabled(true);
        v2.getBtnListar().setEnabled(true);
        v2.getBtneliminar().setEnabled(false);
        v2.getBtnmodificar().setEnabled(false);
        v2.getTxtnombre().setEnabled(true); 
        v2.getTxtnomper().setEnabled(true);
        v2.getTxtrol().setEnabled(true);
        v2.getTxtgenero().setEnabled(true);
    }//GEN-LAST:event_menuCrearPersonajeActionPerformed

    private void menuModificarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificarPersonajeActionPerformed
        escritorio.add(v2);
        v2.setVisible(true);
        v2.getBtnCrear().setEnabled(false);
        v2.getBtnListar().setEnabled(false);
        v2.getBtneliminar().setEnabled(false);
        v2.getBtnmodificar().setEnabled(true);
        v2.getTxtnombre().setEnabled(false); 
        v2.getTxtnomper().setEnabled(true);
        v2.getTxtrol().setEnabled(true);
        v2.getTxtgenero().setEnabled(true);
    }//GEN-LAST:event_menuModificarPersonajeActionPerformed

    private void menuEliminarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarPersonajeActionPerformed
        escritorio.add(v2);
        v2.setVisible(true);
        v2.getBtnCrear().setEnabled(false);
        v2.getBtnListar().setEnabled(false);
        v2.getBtneliminar().setEnabled(true);
        v2.getBtnmodificar().setEnabled(false);
        v2.getTxtnombre().setEnabled(false); 
        v2.getTxtnomper().setEnabled(false);
        v2.getTxtrol().setEnabled(false);
        v2.getTxtgenero().setEnabled(false);
    }//GEN-LAST:event_menuEliminarPersonajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuCrearActor;
    private javax.swing.JMenuItem menuCrearPelicula;
    private javax.swing.JMenuItem menuCrearPersonaje;
    private javax.swing.JMenuItem menuEliminarPersonaje;
    private javax.swing.JMenuItem menuModificarPersonaje;
    // End of variables declaration//GEN-END:variables
}
